services:
  ros_humble:
    image: pedestrian_nav_fixed_v3
    container_name: pedestrian_nav_container
    # This line sets the starting folder
    working_dir: /home/nk/pedestrian_nav_ai
    network_mode: host
    privileged: true
    shm_size: '4gb'
    volumes:
      - .:/home/nk/pedestrian_nav_ai
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:rw
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
      - LIBGL_ALWAYS_SOFTWARE=1
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true
    tty: true
    command: /bin/bash