services:
  ros_humble:
    build: .
    image: pedestrian_nav:humble-gazebo-yolo-stable
    container_name: pedestrian_nav_container

    network_mode: host
    privileged: true
    shm_size: '8gb'

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - __NV_PRIME_RENDER_OFFLOAD=1
      - GZ_RENDER_ENGINE=ogre2
      

    volumes:
      - .:/home/nk/pedestrian_nav_ai
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    stdin_open: true
    tty: true
    command: /bin/bash
